chore(release): 1.13.0
aws-observability/aws-rum-web pull request #355
Opened 2023-02-08 09:59 UTC by ps863

This PR releases 1.13.0

The following changes are made: 

Features:

* Increase stack trace length ([#313](https://github.com/aws-observability/aws-rum-web/pull/313))
([28e34c5](https://github.com/aws-observability/aws-rum-web/commit/28e34c5ad541e1fc1e0b12c1a937289df5911791))

* Create a session ID when cookies are disabled ([#314](https://github.com/aws-observability/aws-rum-web/pull/314))
([6943587](https://github.com/aws-observability/aws-rum-web/commit/6943587259b8d7623742656199dc26b26b5bcd5d))

* referrer ([#327](https://github.com/aws-observability/aws-rum-web/pull/327))
([a414c92](https://github.com/aws-observability/aws-rum-web/commit/a414c9265b37f9eafe7ae6475fe71357beadbcfc))

* webclient version and installation method ([#321](https://github.com/aws-observability/aws-rum-web/pull/321))
([97c543a](https://github.com/aws-observability/aws-rum-web/commit/97c543a13d845bb4c2683c2b6b85ac97237fa410))

* Time Spent On Page ([#341](https://github.com/aws-observability/aws-rum-web/pull/341))
([d1c3b17](https://github.com/aws-observability/aws-rum-web/commit/d1c3b176db0d070faa44cd547c42ed907167d51b))

Fix:

* Add type to recordJsErrorEvent parameter ([#339](https://github.com/aws-observability/aws-rum-web/pull/339))
([2ee6ffa](https://github.com/aws-observability/aws-rum-web/commit/2ee6ffa115f448e5f43b18b6af6f58750c35e544))

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-08 19:13 UTC, adebayor123 approved these changes
LGTM - assuming these features are ready from DP/CP

2023-02-08 23:49 UTC, qhanam requested changes

2023-02-08 23:49 UTC, qhanam commented on CHANGELOG.md
> +* referrer ([#327](https://github.com/aws-observability/aws-rum-web/issues/327)) ([a414c92](https://github.com/aws-observability/aws-rum-web/commit/a414c9265b37f9eafe7ae6475fe71357beadbcfc))
issue: What this change does isn't clear from the description. Same with lines 13 and 14.

In retrospect, we should catch things like this during code review, as the commit message does not adhere to convention.

2023-02-09 16:48 UTC, qhanam approved these changes

2023-02-09 16:48 UTC, qhanam commented on CHANGELOG.md
> +* Record the webclient version and web client installation method in event metadata([#321](https://github.com/aws-observability/aws-rum-web/issues/321)) ([97c543a](https://github.com/aws-observabilit
```suggestion
* Record the webclient version and web client installation method ([#321](https://github.com/aws-observability/aws-rum-web/issues/321)) ([97c543a](https://github.com/aws-observability/aws-rum-web/commit/97c543a13d845bb4c2683c2b6b85ac97237fa410))
```

2023-02-09 16:48 UTC, qhanam commented on CHANGELOG.md
> +* Record referrer and referrer's domain in the event details of a page-view-event ([#327](https://github.com/aws-observability/aws-rum-web/issues/327)) ([a414c92](https://github.com/aws-observability
```suggestion
* Record referrer and referrer's domain ([#327](https://github.com/aws-observability/aws-rum-web/issues/327)) ([a414c92](https://github.com/aws-observability/aws-rum-web/commit/a414c9265b37f9eafe7ae6475fe71357beadbcfc))
```

2023-02-09 16:48 UTC, qhanam commented on CHANGELOG.md
> +* Record time spent on a page in the event details of a page-view-event ( ([#341](https://github.com/aws-observability/aws-rum-web/pull/341))([d1c3b17](https://github.com/aws-observability/aws-rum-we
```suggestion
* Record time spent on a page ( ([#341](https://github.com/aws-observability/aws-rum-web/pull/341))([d1c3b17](https://github.com/aws-observability/aws-rum-web/commit/d1c3b176db0d070faa44cd547c42ed907167d51b))
```

2023-02-23 21:00 UTC, merged