fix: Save deserialized credential object to Authentication member
aws-observability/aws-rum-web pull request #436
Opened 2023-08-18 22:09 UTC by adebayor123

## Details
Currently in our Authentication and EnhancedAuthentication, we save credential object as serialized string values. Then, as we read the serialized string from Storage, we parse the string into a Credential object.

However, in AnonymousStorageCredentialsProvider, we overwrite the local member variable credential with the serialized string instead of the parsed object. As a result, any situation that requires reading of the credential from storage leads to: TypeError: this.credentials.expiration.getTime is not a function.

This PR removes the unnecessary step to overwrite the local member this.credential with the serialized string.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-18 23:56 UTC, ps863 approved these changes

2023-08-19 01:06 UTC, qhanam requested changes

2023-08-19 01:06 UTC, qhanam commented on src/dispatch/EnhancedAuthentication.ts
> +                };
issue: We need unit tests to cover the new behavior (here and in Authentication.ts).

I think this change introduces a bug. Cover the following cases:
1. When credentials are read from storage.
2. When credentials are read from storage, and then read from the member variable.

2023-08-21 17:57 UTC, qhanam commented
I've pushed a patch for EnhancedAuthentication.ts:
1. Add type to `credentials` local variable
2. Add `return` statement when rejecting
3. Fix expiration (to be date object) in resolved value
4. Added unit tests

2023-08-22 05:12 UTC, qhanam commented on src/dispatch/__tests__/Authentication.test.ts
> +    test('when credentials are read from storage then the member variable stores the expiration as a date object', async () => {
nit: This test will pass under certain conditions when it should fail (i.e., false negative).

Specifically, when `this.credentials.expiration` is `undefined`, and the `expiration` property of the value returned by `AnonymousStorageCredentialsProvider` is a `Date` object. When this happens, control flow will reach `AnonymousCognitoCredentialsProvider`, and the test needs a way to distinguish the value returned here from the expected value.

You can fix this by mocking the response of getCredentials, like was done in [EnhancedAuthentication.test.ts here](https://github.com/aws-observability/aws-rum-web/pull/436/files#diff-94a33512cc69b461d93e786b0cfc32e12f8767a11831604e38300860eb1ffba7R348-R355).

2023-08-22 05:13 UTC, qhanam approved these changes

2023-08-23 16:41 UTC, merged